include $(TOPDIR)/rules.mk

LUCI_TITLE:=CB-Shield LuCI Pages
LUCI_DEPENDS:=+luci-base
LUCI_DESCRIPTION:=CB-Shield 定制化 LuCI 业务页面与样式
PKG_LICENSE:=MIT

include $(TOPDIR)/feeds/luci/luci.mk

$(eval $(call BuildPackage,luci-theme-cbshield))
