config main 'main'
    option enabled '1'
    option auto_repair '1'
    option interval '60'
    option check_proxy '1'
    option check_riskcontrol '1'
    option check_portal '1'
    option check_wifi '1'
