config global 'global'
    option enabled '1'
    option interval '300'

config shop 'shop1'
    option template 'direct'
    option current 'direct'
    option schedule 'always'
    option sched_blocked '0'
    option whitelist ''
    option egress 'direct'
    option up_kbit '0'
    option down_kbit '0'

config shop 'shop2'
    option template 'direct'
    option current 'direct'
    option schedule 'always'
    option sched_blocked '0'
    option whitelist ''
    option egress 'direct'
    option up_kbit '0'
    option down_kbit '0'

config shop 'shop3'
    option template 'direct'
    option current 'direct'
    option schedule 'always'
    option sched_blocked '0'
    option whitelist ''
    option egress 'direct'
    option up_kbit '0'
    option down_kbit '0'

config shop 'shop4'
    option template 'direct'
    option current 'direct'
    option schedule 'always'
    option sched_blocked '0'
    option whitelist ''
    option egress 'direct'
    option up_kbit '0'
    option down_kbit '0'

config shop 'shop5'
    option template 'direct'
    option current 'direct'
    option schedule 'always'
    option sched_blocked '0'
    option whitelist ''
    option egress 'direct'
    option up_kbit '0'
    option down_kbit '0'
