config main 'main'
    option required '1'
    option enforce_password_change '1'
    option proxy_enabled '0'
    option proxy_type 'none'
    option openclash_subscription ''
    option openclash_profile 'cbshield'
    option openclash_mode 'rule'
    option openclash_operation_mode 'fake-ip'
