name: Build CrossBorderShield Q30

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev

      - name: Clone Source
        run: |
          git clone --depth 1 https://github.com/immortalwrt/immortalwrt -b openwrt-23.05 master

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            master/staging_dir
            master/build_dir
            master/dl
          key: ${{ runner.os }}-openwrt-q30-v4-${{ hashFiles('diy-part2.sh') }}
          # 继承刚才跑完的成功缓存，实现极速打包
          restore-keys: |
            ${{ runner.os }}-openwrt-q30-v4-
            ${{ runner.os }}-openwrt-q30-v3-

      - name: Update Feeds
        run: |
          chmod +x diy-part1.sh
          cp diy-part1.sh master/
          cd master
          ./diy-part1.sh
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Config & DIY
        run: |
          # 1. 绝对锁定 Q30 Pro 架构
          echo "CONFIG_TARGET_mediatek=y" > master/.config
          echo "CONFIG_TARGET_mediatek_filogic=y" >> master/.config
          echo "CONFIG_TARGET_MULTI_PROFILE=y" >> master/.config
          echo "CONFIG_TARGET_DEVICE_mediatek_filogic_DEVICE_jcg_q30_pro=y" >> master/.config
          
          # 2. 强制关闭软件包加密签名，绕过报错
          echo "CONFIG_SIGNED_PACKAGES=n" >> master/.config
          
          rm -rf master/tmp
          
          chmod +x diy-part2.sh
          cp diy-part2.sh master/
          [ -d "images" ] && cp -r images master/
          cd master
          ./diy-part2.sh
          
          make defconfig

      - name: Download & Compile
        run: |
          cd master
          make download -j8
          make -j$(nproc) || make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: CB-Shield-Pro-Firmware
          # 【终极抓取策略】：不管叫什么名字，把所有的 .bin 和 .itb 固件全部打包带走
          path: |
            master/bin/targets/*/*/*.bin
            master/bin/targets/*/*/*.itb
