name: Build CrossBorderShield Q30

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev

      - name: Clone Source
        run: |
          git clone --depth 1 https://github.com/immortalwrt/immortalwrt -b openwrt-23.05 master

      - name: Update Feeds
        run: |
          chmod +x diy-part1.sh
          cp diy-part1.sh master/
          cd master
          ./diy-part1.sh
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Config & DIY
        run: |
          cp seed.config master/.config
          chmod +x diy-part2.sh
          cp diy-part2.sh master/
          [ -d "images" ] && cp -r images master/
          cd master
          ./diy-part2.sh
          make defconfig

      - name: Download & Compile
        run: |
          cd master
          make download -j8
          make -j$(nproc) || make -j1 V=s

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: CB-Shield-Pro-Firmware
          # 修正后的通配符路径，确保抓取所有生成的固件
          path: master/bin/targets/*/*/*.bin
